name: ESLint

on:
  push:
    branches: [ main, master ] # Adjust branch names if necessary
  pull_request:
    branches: [ main, master ] # Adjust branch names if necessary

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or a version suitable for the project, check package.json engines if specified

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
